# Generated by Django 5.0 on 2023-12-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
